name: Rust Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust (stable) with llvm-tools
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: llvm-tools-preview

    - name: Install grcov
      run: cargo install grcov

    - name: Clean before test
      run: cargo clean

    - name: Run tests with coverage
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-C instrument-coverage'
        LLVM_PROFILE_FILE: 'coverage-%p-%m.profraw'
      run: cargo test --verbose

    - name: Generate coverage report
      run: |
        grcov . --binary-path ./target/debug/ \
          -s . -t lcov --branch --ignore-not-existing \
          -o lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: lcov.info
        verbose: true
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
